# Generated by Django 6.0 on 2026-01-22 21:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient_portal", "0007_merge_20260122_2341"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfflineDataCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("symptom_logs", models.JSONField(blank=True, default=list)),
                ("alerts", models.JSONField(blank=True, default=list)),
                ("treatment_plans", models.JSONField(blank=True, default=list)),
                ("notifications_prefs", models.JSONField(blank=True, default=dict)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("cache_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_cache",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Data Cache",
                "verbose_name_plural": "Offline Data Caches",
                "db_table": "offline_data_cache",
            },
        ),
        migrations.CreateModel(
            name="OfflineSyncQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("symptom_log", "Symptom Log"),
                            ("alert_read", "Alert Marked Read"),
                            ("alert_read_all", "All Alerts Marked Read"),
                            (
                                "notification_preference",
                                "Notification Preference Update",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("operation_data", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Sync"),
                            ("syncing", "Syncing"),
                            ("synced", "Synced"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=5)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("client_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_sync_queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offline Sync Queue Item",
                "verbose_name_plural": "Offline Sync Queue Items",
                "db_table": "offline_sync_queue",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["patient", "status", "created_at"],
                        name="offline_syn_patient_ac1f7c_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="offline_syn_status_d1240b_idx",
                    ),
                ],
            },
        ),
    ]
