# Generated by Django 6.0 on 2026-01-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0008_add_offline_sync_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='pdf_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of PDF', max_length=64),
        ),
    ]
