# Generated by Django 6.0 on 2026-02-10 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0009_alter_prescription_pdf_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_number', models.IntegerField(help_text='Sequential token number for this doctor')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='consultation_tokens/')),
                ('pdf_hash', models.CharField(blank=True, help_text='SHA-256 hash of PDF', max_length=64)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Blockchain transaction hash', max_length=66)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether hash is confirmed on blockchain')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_token', to='patient_portal.consultation')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tokens', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation Token',
                'verbose_name_plural': 'Consultation Tokens',
                'db_table': 'consultation_tokens',
                'ordering': ['-created_at'],
                'unique_together': {('doctor', 'token_number')},
            },
        ),
    ]
