# Generated by Django 6.0 on 2026-01-31 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_doctorprofile_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram Chat ID for notifications', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telegram_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Enable Telegram notifications'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='Telegram username', max_length=100, null=True),
        ),
    ]
